name: Deploy to Scaleway Container Registry

on:
  workflow_dispatch:

#on:
#  release:
#    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Install NPM
        working-directory: frontend
        run: npm install

      - name: Build frontend with NPM
        working-directory: frontend
        run: npm run build

      - name: Get version
        id: version
        run: |
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_API_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
      
      - name: Build and push image with Spring Boot buildpacks
        run: |
          ./mvnw clean spring-boot:build-image -DskipTests \
            -Dspring-boot.build-image.imageName=${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/chorely:$VERSION \
            -Dspring-boot.build-image.publish=true

          docker tag ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/chorely:$VERSION ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/chorely:latest
          docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/chorely:latest
